
OBJECTS = 
CFLAGS = -std=c99 -g -Wall  
LDLIBS = 
CC=gcc


all: memory_segments 

memory_segments: memory_segments.c
	$(CC) $(CFLAGS) $(LDLIBS) -o memory_segments memory_segments.c 

clean:
	rm memory_segments 

