
CREATE TABLE user 
(
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	firstname VARCHAR(256) NOT NULL,
	lastname VARCHAR(256) NOT NULL,
	username VARCHAR(256) NOT NULL,
	password VARCHAR(256) NOT NULL
) ENGINE = INNODB;


